### ISSUE TITLE
Sparse view selection for dataset.

### ISSUE THREAD

**Issue by Qjiasheng** [GaussianObject/GaussianObject#25]
Hello! Great work!

I'm interested in sparse view selection. I noticed that the indices of selected views are stored in `sparse_X.txt` files. How do you sample sparse views from a group of original views? What's the principle behind the selection? The selected views are expected to be uniform and cover the object as much as possible, right? And any code to do this?

**Comment by GaussianObject** [comment]
Hello! Thank you for your kind words and interest in our work!

Regarding sparse view selection, we have discussed this topic in #10. Part of our training set is inherited from previous sparse view experiments, while the other part was selected casually. Specifically, we utilized a python script based on `camtools` and `open3d` to visually display the camera positions in space through a GUI, allowing us to manually choose a few cameras that could cover the object from various angles as comprehensively as possible.

We haven't open-sourced this part of the code since the dataset has already been made public. However, you can refer to this script available at a [gists link](https://gist.github.com/GaussianObject/bd2bacaa1cfa739d2d0d98cd5f8a8e4f) to match your own data.

We hope this answers your question, and please don't hesitate to reach out if you have further queries!

**Comment by Qjiasheng** [comment]
> Hello! Thank you for your kind words and interest in our work!
> 
> Regarding sparse view selection, we have discussed this topic in #10. Part of our training set is inherited from previous sparse view experiments, while the other part was selected casually. Specifically, we utilized a python script based on `camtools` and `open3d` to visually display the camera positions in space through a GUI, allowing us to manually choose a few cameras that could cover the object from various angles as comprehensively as possible.
> 
> We haven't open-sourced this part of the code since the dataset has already been made public. However, you can refer to this script available at a [gists link](https://gist.github.com/GaussianObject/bd2bacaa1cfa739d2d0d98cd5f8a8e4f) to match your own data.
> 
> We hope this answers your question, and please don't hesitate to reach out if you have further queries!

Thank you for your clear explanations and codes.
