### ISSUE TITLE
Extra hugging face model need to be downloaded.

### ISSUE THREAD

**Issue by nickle-fang** [GaussianObject/GaussianObject#3]
In file `download_hf_models.py`, `runwayml/stable-diffusion-v1-5` and `lllyasviel/ControlNet-v1-1` is downloaded in advance. But when I ran the script `train_lora.py`, errors occured like below:
``` bash
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
```
So I wonder if I need to download the model 'openai/clip-vit-large-patch14' and where should I put the file. 
Thanks a lot for your excellent work and the code sharing!

**Comment by GaussianObject** [comment]
Thank you for your feedback and kind words!

The CLIP model within ControlNet is defined at:

https://github.com/GaussianObject/GaussianObject/blob/c087d48a551649fe30e2ed24a74eec80690b68ab/ldm/modules/encoders/modules.py#L88-L100

Therefore, the `transformers` module should automatically download the model weights into `~/.cache/huggingface/hub`. It's actually unusual to encounter an `OSError` since the code is designed to access CLIP weights from the Hugging Face Hub directly.

To troubleshoot, please try running the following code:

```py
from transformers import CLIPTokenizer, CLIPTextModel

version="openai/clip-vit-large-patch14"
tokenizer = CLIPTokenizer.from_pretrained(version)
transformer = CLIPTextModel.from_pretrained(version)
```

and check if any errors occur.

**Comment by nickle-fang** [comment]
Thanks for your prompt reply! I solve the problem by using the mirror [website](https://hf-mirror.com/) of hugging face.
`HF_ENDPOINT=https://hf-mirror.com python train_lora.py`

**Comment by 2019211753** [comment]
zIT

> Thanks for your prompt reply! I solve the problem by using the mirror [website](https://hf-mirror.com/) of hugging face. `HF_ENDPOINT=https://hf-mirror.com python train_lora.py`



> Thanks for your prompt reply! I solve the problem by using the mirror [website](https://hf-mirror.com/) of hugging face. `HF_ENDPOINT=https://hf-mirror.com python train_lora.py`

Thank you. It works.
