### ISSUE TITLE
diff-gaussian-rasterization-w-pose not being found

### ISSUE THREAD

**Issue by anekha** [GaussianObject/GaussianObject#49]
Hello,

I have tried for over 2 weeks to install GaussianObject. I am using CUDA 11.8 and python 3.11 as per instructions on the Github page but each time I am getting the error during training where it says it cannot find the submodule and I do not know what to do at this point as I have tried installing it again 

Traceback (most recent call last):
  File "/content/GaussianObject/train_gs.py", line 26, in <module>
    from gaussian_renderer import network_gui
  File "/content/GaussianObject/gaussian_renderer/__init__.py", line 15, in <module>
    from diff_gaussian_rasterization_w_pose import GaussianRasterizationSettings as GaussianRasterizationSettings_w_pose, GaussianRasterizer as GaussianRasterizer_w_pose
ModuleNotFoundError: No module named 'diff_gaussian_rasterization_w_pose'

I would be grateful for any help. I was working on the shared colab notebook but I think versions are out of date so I created a new one based on that.
Thanks

**Comment by eternalland** [comment]
same question, how can i resolve it?

**Comment by seulqxq** [comment]
same

**Comment by eternalland** [comment]
@anekha @seulqxq 

Because the installation name of file "/submodules/diff_gaussian_rasterization" and file "/submodules/diff-gaussian-rasterization-w-pose" are the same, they conflict.

1. change all the word "diff_gaussian_rasterization" to "diff_gaussian_rasterization_w_pose" in this file "/submodules/diff-gaussian-rasterization-w-pose/setup.py"
2. change the filename of file "diff_gaussian_rasterization" to "diff_gaussian_rasterization_w_pose" under this path "/submodules/diff-gaussian-rasterization-w-pose"
3. pip install ./submodules/diff-gaussian-rasterization-w-pose
4. test: 
$python
 import diff_gaussian_rasterization_w_pose

**Comment by anekha** [comment]
@eternalland thanks - trying this now. Hope it works

**Comment by anekha** [comment]
@eternalland Thanks a lot, this worked
